### ISSUE TITLE
[Bug]: 打开插件后，ob右上角的最大化，最小化，关闭按钮都消失了，关闭插件就出来了

### ISSUE THREAD

**Issue by sunnyvGitHub** [Quorafind/Obsidian-Double-Click-Tab#12]
### Bug Description

打开插件后，ob右上角的最大化，最小化，关闭按钮都消失了，关闭插件就又显示出来了

### Relevant Screenshot

![double](https://user-images.githubusercontent.com/34822642/206643738-333058cb-a58e-49a3-b5e3-3eafb0a19fa2.png)

### Obsidian Version

1.0.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Moyf** [comment]
```css
.titlebar-button-container.mod-right {
/*	width: var(--size-4-2);*/
	transition: width 275ms var(--anim-motion-swing);
}
```

插件的 css 里有一个这个设置，把按钮区域的宽度设成 8 像素了……
像上面一样把那行 `width` 注释掉就能恢复。

> 老实说很奇怪这里为啥要这样设置 🤔
